### ISSUE TITLE
Controlnet support?

### ISSUE THREAD

**Issue by rossman22590** [ryzvision/prodia.js#2]
can i use this library for controlnet?

**Comment by flameface** [comment]
![image](https://github.com/A3PIRE/prodia.js/assets/84311327/9308d4b5-1ad0-41e9-ba73-108562884571)
After Prodia adds control net support, I will update the package.

**Comment by rossman22590** [comment]
i believe it is out of beta will you support SDXL too?

**Comment by flameface** [comment]
@rossman22590 we have add all things from control net to sdxl in latest version
