### ISSUE TITLE
New Model Support

### ISSUE THREAD

**Issue by rossman22590** [ryzvision/prodia.js#3]
🪄 Dreamshaper 7 - A good model for fantasy portraits
🪄 Eimis Anime Diffusion - A strong anime model
🪄 MeinaMix Meina V11 - A merged and mixed model of different anime models
🪄 Portrait+ V1 - A model trained on a diverse set of close to medium range portraits of people.
🪄 Realistic Vision V4.0 - A strong model for realistic portraits
🪄 Redshift Diffusion V1.0 - A model trained on high resolution 3D artworks.
🪄 Anything V5 - Its back!  Everyones favorite Anime model

**Comment by flameface** [comment]
Thanks, i will add it.
