### ISSUE TITLE
Modles

### ISSUE THREAD

**Issue by Grimfoxy19883** [ryzvision/prodia.js#4]
How do I see all the modals like 
Dreamshaper 7,
 Eimis Anime Diffusion, How do i know what to type into model: 
for it  generate a image in that model.

**Comment by Grimfoxy19883** [comment]
Why I'm asking is because I can't find the model for the Following "
Dreamshaper 7
Eimis Anime Diffusion 
MeinaMix Meina V11 
 Portrait+ V1
 Realistic Vision V4.0
 Redshift Diffusion V1.0
 Anything V5" - I can't Find the appropriate models in the "https://prodia.js.org/" docs

**Comment by flameface** [comment]
Sorry as i haven't mention in docs

```js
const { Prodia } = require("prodia.js");
const prodia = new Prodia("API-KEY");

const getModels = await prodia.getModels();

console.log(getModels)
```

This will give you a list of all availabe models in prodia
